### ISSUE TITLE
 Api call failed: {"error":"Forbidden request"}

### ISSUE THREAD

**Issue by jpmangoit** [deepak786/intercom_flutter#446] opened 2024-07-09 07:47 UTC
run the example app, now i'm getting this error : Api call failed: {"error":"Forbidden request"}
code :
Center(
          child: TextButton(
            onPressed: () async {
              
              await Intercom.instance.loginIdentifiedUser(
                email: 'jp@mangoitsolutions.com',
              );
              Intercom.instance.displayMessenger();
            },
            child: Text('Show messenger'),
          ),
        ),
      ),
      
after changing the code: 

 await Intercom.instance.loginUnidentifiedUser(
                  statusCallback: IntercomStatusCallback(
                onSuccess: () => print('success'),
                onFailure: (error) => print(error),
              ));
              Intercom.instance.displayMessenger();
             
 still getting same error

**Comment by deepak786** [comment] 2024-07-10 20:11
Did you change the Intercom keys in the example app here https://github.com/v3rm0n/intercom_flutter/blob/ff065c5f2998e12ad9113ec1b9776f0e7f6c63a6/intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MyApp.kt#L12

**Comment by deepak786** [comment] 2024-07-10 20:13
Duplicate of https://github.com/v3rm0n/intercom_flutter/issues/392

**Closed as completed by deepak786** 2024-07-10 20:13 UTC
Labels: platform-android

**Comment by aghyad97** [comment] 2024-08-01 10:44
Please check out my comment here hoping it will solve the issue for you

https://github.com/v3rm0n/intercom_flutter/issues/392#issuecomment-2262724339
