### ISSUE TITLE
Error when using sendTokenToIntercom

### ISSUE THREAD

**Issue by Icety** [deepak786/intercom_flutter#52] opened 2019-12-29 12:54 UTC
Whenever I try to use the sendTokenToIntercom command I get the following error on ios: 
`MissingPluginException(No implementation found for method sendTokenToIntercom on channel maido.io/intercom.`

Same result for both 2.0.7 and 2.0.5-v2 and Flutter version 1.9.1

**Comment by BasedMusa** [comment] 2019-12-29 20:37
I'm also experiencing this, requires immediate attention.
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method sendTokenToIntercom on channel maido.io/intercom)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      Intercom.sendTokenToIntercom (package:intercom_flutter/intercom_flutter.dart:117:21)
#2      _CloudMessagingInterface.setupIntercomPushNotifications (package:qweex/utils/firebase_interface.dart:790:16)
<asynchronous suspension>
#3      _LoginPageState._handleSuccessfulLogin (package:qweex/pages/login_page.dart:180:12)
<asynchronous suspension>
#4      _LoginPageState._login (package:qweex/pages/login_page.dart:146:9)
```

**Comment by BasedMusa** [comment] 2020-01-06 20:57
My client and I were looking forward to releasing this past weekend, but this issue stopped us, @v3rm0n @Zazo032 How soon can one of you please have a look on this?

**Comment by Spikes042** [comment] 2020-01-07 14:01
Duplicate of #29

**Comment by Zazo032** [comment] 2020-01-10 16:23
That implementation is here: https://github.com/v3rm0n/intercom_flutter/blob/master/android/src/main/kotlin/io/maido/intercom/IntercomFlutterPlugin.kt#L145

Did you try `flutter clean`, `flutter packages get` and then `flutter run`? Is that also happening on latest stable or master version of Flutter?

**Comment by Spikes042** [comment] 2020-01-10 17:11
They're seeing this on iOS, not Android.
iOS has not been implemented

**Comment by Zazo032** [comment] 2020-01-13 17:24
Didn't notice this was iOS specific, closing for now as a duplicate, as you said. Meanwhile, you can try this workaround: https://github.com/v3rm0n/intercom_flutter/issues/29#issuecomment-553743983

As always, PRs are welcome and really appreciated if you want to develop that feature.

**Closed as completed by Zazo032** 2020-01-13 17:24 UTC
Labels: platform-ios
