### ISSUE TITLE
MissingPluginException(No implementation found for method sendTokenToIntercom on channel maido.io/intercom)

### ISSUE THREAD

**Issue by himalrandeniya** [deepak786/intercom_flutter#71] opened 2020-04-15 21:10 UTC
Hi team,
I am getting the above error when calling .sendTokenToIntercom with an FCM token.

package v: intercom_flutter: ^2.2.0

**Comment by rfitz123** [comment] 2020-04-24 03:58
Having the same issue with v2.2.0

**Comment by rfitz123** [comment] 2020-04-24 22:36
@v3rm0n Have you or any collaborators seen this issue? I still haven't been able to find any leads.

**Comment by Spikes042** [comment] 2020-04-25 01:10
You should be seeing this only on iOS because it hasn't been implemented.

Duplicate of #29

**Closed as completed** 2020-08-19 17:17 UTC
