### ISSUE TITLE
 [Android] Fatal Exception: java.lang.RuntimeException 

### ISSUE THREAD

**Issue by yisusparkr** [deepak786/intercom_flutter#249] opened 2022-07-21 18:59 UTC
Hi, we are getting the following `Early Crash` on Android in production.<br>
<img width="1295" alt="imagen" src="https://user-images.githubusercontent.com/43246999/180294699-7f1b1948-8efd-4e4b-ae55-2dd750d493c3.png">

I was researching and found that we have to initialize Intercom before running the `runApp` method and be sure that widgets are initialized, but we initialize Intercom just when tapping a button.<br>

```dart
@LazySingleton(as: IntercomFacade, env: [Env.production, Env.development])
class IntercomFacadeImpl implements IntercomFacade {
  @override
  Future<void> init(covariant UserModel user, String? token) async {
    await Intercom.instance.initialize(
      EnvironmentConfig.intercom_appid,
      iosApiKey: EnvironmentConfig.intercom_ios_apikey,
      androidApiKey: EnvironmentConfig.intercom_android_apikey,
    );
    await Intercom.instance.loginIdentifiedUser(
      email: user.email,
    );
    await Intercom.instance.updateUser(
        // ignore: dead_null_aware_expression
        email: user.email,
        name: user.fullName,
        phone: user.phone,
        userId: user.id.toString());
    if (token != null) {
      await Intercom.instance.sendTokenToIntercom(token);
    }
  }
```

- **Plugin version:** `intercom_flutter: ^7.3.0`
- **Flutter version:** `2.10.5`
- **Android versions:** 9, 10, 11 and 12
- **Devices:** Samsung, Yulong, Motorola and LGE

**Comment by deepak786** [comment] 2022-08-22 11:26
@dev-abdiel Yes, it is necessary to initialize the Intercom before the `runApp` method.

Actually, It should be initialized in the `onCreate` of the application class on the Android side but in Flutter we are initializing it on demand i.e before the `runApp` method.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // TODO: make sure to add keys from your Intercom workspace.
  await Intercom.instance.initialize(
    'appId',
    androidApiKey: 'androidApiKey',
    iosApiKey: 'iosApiKey',
  );
  runApp(SampleApp());
}
```

By the way, there is already a similar issue opened https://github.com/v3rm0n/intercom_flutter/issues/120

**Comment by deepak786** [comment] 2022-08-22 11:27
So closing this as duplicate of https://github.com/v3rm0n/intercom_flutter/issues/120

**Closed as completed by deepak786** 2022-08-22 11:27 UTC
Labels: platform-android
