### ISSUE TITLE
Present an Article Programmatically

### ISSUE THREAD

**Issue by skom-42** [deepak786/intercom_flutter#136] opened 2021-03-30 15:47 UTC
I added displayArticle() method to IntercomeFlutterPlugin.kt and method presentArticle() for IOS. 
After that I'm tryin to call it from intercom_flutter.dart but have the same issue for both 
<img width="1449" alt="Снимок экрана 2021-03-30 в 18 36 50" src="https://user-images.githubusercontent.com/43013509/113017391-0fb48280-9188-11eb-90f5-e1b3b7ac720c.png">

Could you please add this functionality to the flutter plugin.
This is already implemented for native Android and IOS apps

**Comment by Zazo032** [comment] 2021-03-30 16:06
That error means, after adding native code, you should do a fresh run of the app. Try that and see if it works.

**Comment by deepak786** [comment] 2021-05-14 19:28
https://developers.intercom.com/installing-intercom/docs/android-configuration#section-present-an-article-programmatically

**Comment by deepak786** [comment] 2021-05-14 19:31
closing this as a duplicate of https://github.com/v3rm0n/intercom_flutter/issues/116

**Closed as completed by deepak786** 2021-05-14 19:31 UTC
Labels: enhancement
