### ISSUE TITLE
[iOS] Can't register only with email

### ISSUE THREAD

**Issue by marcuslma** [deepak786/intercom_flutter#14] opened 2019-04-12 17:38 UTC
Hello, I am getting the following error when trying to register with email on iOS

`Runner[28519:158401] [Intercom] ERROR - 'userId' parameter must be an NSString and can't be nil or empty`

**Comment by Spikes042** [comment] 2019-04-13 01:27
Duplicate of #13

**Comment by Spikes042** [comment] 2019-04-13 04:58
#
Duplicate of #13

**Comment by zanuka** [comment] 2019-04-14 23:20
Having the same issue @marcuslma ... works fine on Android, going to test #15 on my fork...

**Comment by v3rm0n** [comment] 2019-04-25 19:48
Fixed in `2.0.2`

**Closed as completed by v3rm0n** 2019-04-25 19:48 UTC
