### ISSUE TITLE
Intercom 401 ERROR 

### ISSUE THREAD

**Issue by ryder247** [deepak786/intercom_flutter#132] opened 2021-03-22 08:02 UTC
What could make me get this exception?
[Intercom] ERROR - Tried to fetch the home screen but there was a network error (401) - Request failed: unauthorized (401)]

**Comment by Zazo032** [comment] 2021-03-22 08:07
You may be using a wrong API key, or Intercom API may be down at that moment. Doesn't seem to be an issue with the plugin, can you add some more information? Which device experienced this issue, Android version, plugin version, a code sample to try to reproduce it would also be great.

**Comment by ryder247** [comment] 2021-03-22 10:22
Thank you for the rapid response.
The thing is it's probably not from this plugin. we are already using it in production and without any recent deployment to AppStore or PlayStore. What we have done recently though is a plan upgrade. I am not entirely sure how that too could cause such an error. you should also know that when I use the registerUnidentifiedUser everything works fine.

**Comment by Zazo032** [comment] 2021-03-22 10:26
You can try asking Intercom directly what's happening, either through their support chat or their [repository](https://github.com/intercom) in case it's an error with the framework. I'm closing this since doesn't sound like an error with the plugin, since this is just a bridge between Flutter and native SDKs.

**Closed as completed by Zazo032** 2021-03-22 10:26 UTC
