### ISSUE TITLE
It is impossible to archive iOS build

### ISSUE THREAD

**Issue by Mounix99** [deepak786/intercom_flutter#326] opened 2023-07-03 15:43 UTC
Without updating anything, today it is impossible to archive ios project from both my machine and Bitrise service. There is the same error 

`/Users/[REDACTED]/.pub-cache/hosted/pub.dev/intercom_flutter-7.8.1/ios/Classes/IntercomFlutterPlugin.m:2:9: fatal error: 'Intercom/Intercom.h' file not found (exit code: 1)`

Last week's builds were perfectly built. Do you know what can be the reason for that ?

**Comment by oguibueno** [comment] 2023-07-03 15:59
Hey! I'm having the same issue when trying to build it. 

`Lexical or Preprocessor Issue (Xcode): 'Intercom/Intercom.h' file not found
/Users/XPTO/.pub-cache/hosted/pub.dartlang.org/intercom_flutter-7.6.5/ios/Classes/IntercomFlutterPlugin.m:1:8`

I've noticed this line is removed from `project.pbxproj` when installing the pods:

`"${PODS_XCFRAMEWORKS_BUILD_DIR}/Intercom/Intercom.framework/Intercom",`

**Comment by oguibueno** [comment] 2023-07-03 16:05
Try this https://github.com/v3rm0n/intercom_flutter/issues/325#issuecomment-1618595301

**Comment by deepak786** [comment] 2023-07-03 20:01
Possibly duplicate of #325

**Closed as completed by deepak786** 2023-07-03 20:01 UTC
Labels: bug, platform-ios, native-sdk
