### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method sendTokenToIntercom on channel maido.io/intercom)

### ISSUE THREAD

**Issue by TechnoPrashant** [deepak786/intercom_flutter#84] opened 2020-08-17 08:05 UTC
When i run app in ios

**Comment by Spikes042** [comment] 2020-08-19 16:27
duplicate of #29

**Closed as completed** 2020-08-19 17:18 UTC

**Comment by HananKamal-VG** [comment] 2020-09-17 11:56
@Zazo032  When will the new version publish and be available for use ?

**Comment by Zazo032** [comment] 2020-09-17 12:28
> @Zazo032 When will the new version publish and be available for use ?

Hi, it should be available now as `2.2.1` on pub.dev
