### ISSUE TITLE
Issue: App crash when installing with apk file

### ISSUE THREAD

**Issue by vantoan9708** [deepak786/intercom_flutter#475] opened 2024-10-16 11:57 UTC
Hi

Flutter SDK: 3.24.3

using package: intercom_flutter 9.1.1

The app crashes when I click intercomInstance.displayMessenger()

I think the problem will happen whenever I open the intercom

Thank you

**Comment by deepak786** [comment] 2024-11-27 20:37
Maybe duplicate of https://github.com/v3rm0n/intercom_flutter/issues/383

**Closed as completed by deepak786** 2024-11-27 20:37 UTC
Labels: platform-android, crash, support
